### ISSUE TITLE
Plugins doesn't work on Gradle 5.2 after updating to 3.0.0

### ISSUE THREAD

**Issue by sureshg** [JLLeitschuh/ktlint-gradle#201]
```
Gradle : 5.2
ktlintPlugin = "7.0.0"
ktlint = "0.30.0"
kotlin = "1.3.20"
```

The plugin is not working after upgrading to Gradle `5.2` and ktlint-plugin to `3.0.0`

```
* What went wrong:
An exception occurred applying plugin request [id: 'org.jlleitschuh.gradle.ktlint', version: '7.0.0']
> Failed to apply plugin [id 'org.jlleitschuh.gradle.ktlint']
   > Could not create plugin of type 'KtlintPlugin'.
      > Could not generate a decorated class for class org.jlleitschuh.gradle.ktlint.KtlintPlugin.
         > com/android/build/gradle/BaseExtension
```

Stacktrace
```
Caused by: java.lang.NoClassDefFoundError: com/android/build/gradle/BaseExtension
        at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:69)
        at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:55)
        at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:35)
        at org.gradle.internal.instantiation.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:199)
        at org.gradle.internal.instantiation.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:152)
        ... 162 more
Caused by: java.lang.ClassNotFoundException: com.android.build.gradle.BaseExtension
        ... 167 more```

**Comment by JLLeitschuh** [comment]
Due to: https://github.com/gradle/gradle/issues/8411

@Tapchicoma I think we can fix it by moving this method declaration outside of the class and don't scope it to the class.

Kind of a hack, but it should fix it for our users.

https://github.com/JLLeitschuh/ktlint-gradle/blob/3c56f4e8619d0dbb6daba1c9929256390875e1e4/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt#L200-L219
